# Newsletter Workflow Deployment Configuration (Free Tier)
# 
# This configuration runs tasks synchronously without Redis to avoid paid services
# - Tasks run synchronously (no Redis/worker needed)
# - Only the web service is deployed
# - To enable Redis later, add back the Redis and worker services
#
services:
  - type: web
    name: ai-newsletter-web
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install .
    startCommand: uvicorn newsletter.api.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: "10000"
      - key: CELERY_TASK_ALWAYS_EAGER
        value: "true"
      - key: DATABASE_PATH
        value: /tmp/newsletter_tasks.db
      - key: OPENROUTER_API_KEY
        sync: false
      - key: JINA_READER_API_KEY
        sync: false
    healthCheckPath: /healthz
